# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/has_scope/all/has_scope.rbi
#
# has_scope-0.7.2

module HasScope
  def applicable?(string_proc_or_symbol, expected); end
  def apply_scope_to_action?(options); end
  def apply_scopes(target, hash = nil); end
  def call_scope_by_type(type, scope, target, value, options); end
  def current_scopes; end
  def normalize_blanks(value); end
  def parse_value(type, key, value); end
  def self.included(base); end
end
module HasScope::ClassMethods
  def has_scope(*scopes, &block); end
end
