# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/minitest-spec-rails/all/minitest-spec-rails.rbi
#
# minitest-spec-rails-6.0.2

module MiniTestSpecRails
end
module MiniTestSpecRails::DSL
  def described_class; end
  def self.included(klass); end
end
module MiniTestSpecRails::DSL::ClassMethods
  def after(_type = nil, &block); end
  def before(_type = nil, &block); end
  def describe(*args, &block); end
  def described_class; end
  def test(name, &block); end
end
class MiniTestSpecRails::Railtie < Rails::Railtie
end
