# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/openlibrary/all/openlibrary.rbi
#
# openlibrary-1.0.0

module Openlibrary
  def self.version_string; end
end
