# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/possessive/all/possessive.rbi
#
# possessive-1.0.1

class String
  def possessive; end
end
module Possessive
end
