inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rails.yml

inherit_mode:
  merge:
    - Exclude

Metrics/BlockLength:
  Exclude:
    - config/routes.rb

Rails/OutputSafety:
  Enabled: false

Rails/UniqueValidationWithoutIndex:
  Enabled: false

Style/WordArray:
  Enabled: false

AllCops:
  Exclude:
  # Exclude warning that "change_column is not reversible". This change could be complicated
  # to reverse (data may need to be altered), and reversing should not be necessary.
    - db/migrate/20210806180637_change_user_image_url_data_type.rb
